/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings.workspaces'
import { Route as SettingsUpdatesRouteImport } from './routes/settings.updates'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSnapShotRouteImport } from './routes/settings.snap-shot'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings.scheduled-tasks'
import { Route as SettingsRecordingRouteImport } from './routes/settings.recording'
import { Route as SettingsQuickAccessRouteImport } from './routes/settings.quick-access'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsPermissionsRouteImport } from './routes/settings.permissions'
import { Route as SettingsOpenSourceLicensesRouteImport } from './routes/settings.open-source-licenses'
import { Route as SettingsMenuBarRouteImport } from './routes/settings.menu-bar'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExternalAppsRouteImport } from './routes/settings.external-apps'
import { Route as SettingsDictationRouteImport } from './routes/settings.dictation'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsCloudUploadsRouteImport } from './routes/settings.cloud-uploads'
import { Route as SettingsCaptureHistoryRouteImport } from './routes/settings.capture-history'
import { Route as SettingsCaptureRouteImport } from './routes/settings.capture'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAnnotationsRouteImport } from './routes/settings.annotations'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as ChatWorkspacesRouteImport } from './routes/_chat.workspaces'
import { Route as ChatServicesRouteImport } from './routes/_chat.services'
import { Route as ChatRecordingsRouteImport } from './routes/_chat.recordings'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatLinkedWorkRouteImport } from './routes/_chat.linked-work'
import { Route as ChatInboxRouteImport } from './routes/_chat.inbox'
import { Route as ChatExternalAppsRouteImport } from './routes/_chat.external-apps'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUpdatesRoute = SettingsUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSnapShotRoute = SettingsSnapShotRouteImport.update({
  id: '/snap-shot',
  path: '/snap-shot',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRecordingRoute = SettingsRecordingRouteImport.update({
  id: '/recording',
  path: '/recording',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsQuickAccessRoute = SettingsQuickAccessRouteImport.update({
  id: '/quick-access',
  path: '/quick-access',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOpenSourceLicensesRoute =
  SettingsOpenSourceLicensesRouteImport.update({
    id: '/open-source-licenses',
    path: '/open-source-licenses',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsMenuBarRoute = SettingsMenuBarRouteImport.update({
  id: '/menu-bar',
  path: '/menu-bar',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExternalAppsRoute = SettingsExternalAppsRouteImport.update({
  id: '/external-apps',
  path: '/external-apps',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDictationRoute = SettingsDictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCloudUploadsRoute = SettingsCloudUploadsRouteImport.update({
  id: '/cloud-uploads',
  path: '/cloud-uploads',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCaptureHistoryRoute = SettingsCaptureHistoryRouteImport.update({
  id: '/capture-history',
  path: '/capture-history',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCaptureRoute = SettingsCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAnnotationsRoute = SettingsAnnotationsRouteImport.update({
  id: '/annotations',
  path: '/annotations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatWorkspacesRoute = ChatWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ChatRoute,
} as any)
const ChatServicesRoute = ChatServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ChatRoute,
} as any)
const ChatRecordingsRoute = ChatRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatLinkedWorkRoute = ChatLinkedWorkRouteImport.update({
  id: '/linked-work',
  path: '/linked-work',
  getParentRoute: () => ChatRoute,
} as any)
const ChatInboxRoute = ChatInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ChatRoute,
} as any)
const ChatExternalAppsRoute = ChatExternalAppsRouteImport.update({
  id: '/external-apps',
  path: '/external-apps',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/external-apps': typeof ChatExternalAppsRoute
  '/inbox': typeof ChatInboxRoute
  '/linked-work': typeof ChatLinkedWorkRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/recordings': typeof ChatRecordingsRoute
  '/services': typeof ChatServicesRoute
  '/workspaces': typeof ChatWorkspacesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/annotations': typeof SettingsAnnotationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capture': typeof SettingsCaptureRoute
  '/settings/capture-history': typeof SettingsCaptureHistoryRoute
  '/settings/cloud-uploads': typeof SettingsCloudUploadsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/dictation': typeof SettingsDictationRoute
  '/settings/external-apps': typeof SettingsExternalAppsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/quick-access': typeof SettingsQuickAccessRoute
  '/settings/recording': typeof SettingsRecordingRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/external-apps': typeof ChatExternalAppsRoute
  '/inbox': typeof ChatInboxRoute
  '/linked-work': typeof ChatLinkedWorkRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/recordings': typeof ChatRecordingsRoute
  '/services': typeof ChatServicesRoute
  '/workspaces': typeof ChatWorkspacesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/annotations': typeof SettingsAnnotationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capture': typeof SettingsCaptureRoute
  '/settings/capture-history': typeof SettingsCaptureHistoryRoute
  '/settings/cloud-uploads': typeof SettingsCloudUploadsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/dictation': typeof SettingsDictationRoute
  '/settings/external-apps': typeof SettingsExternalAppsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/quick-access': typeof SettingsQuickAccessRoute
  '/settings/recording': typeof SettingsRecordingRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/_chat/external-apps': typeof ChatExternalAppsRoute
  '/_chat/inbox': typeof ChatInboxRoute
  '/_chat/linked-work': typeof ChatLinkedWorkRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/_chat/recordings': typeof ChatRecordingsRoute
  '/_chat/services': typeof ChatServicesRoute
  '/_chat/workspaces': typeof ChatWorkspacesRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/annotations': typeof SettingsAnnotationsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capture': typeof SettingsCaptureRoute
  '/settings/capture-history': typeof SettingsCaptureHistoryRoute
  '/settings/cloud-uploads': typeof SettingsCloudUploadsRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/dictation': typeof SettingsDictationRoute
  '/settings/external-apps': typeof SettingsExternalAppsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/menu-bar': typeof SettingsMenuBarRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/quick-access': typeof SettingsQuickAccessRoute
  '/settings/recording': typeof SettingsRecordingRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/updates': typeof SettingsUpdatesRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/external-apps'
    | '/inbox'
    | '/linked-work'
    | '/pull-requests'
    | '/recordings'
    | '/services'
    | '/workspaces'
    | '/projects/$projectKey'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/annotations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/capture'
    | '/settings/capture-history'
    | '/settings/cloud-uploads'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/dictation'
    | '/settings/external-apps'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/menu-bar'
    | '/settings/open-source-licenses'
    | '/settings/permissions'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/quick-access'
    | '/settings/recording'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/updates'
    | '/settings/workspaces'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/external-apps'
    | '/inbox'
    | '/linked-work'
    | '/pull-requests'
    | '/recordings'
    | '/services'
    | '/workspaces'
    | '/projects/$projectKey'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/annotations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/capture'
    | '/settings/capture-history'
    | '/settings/cloud-uploads'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/dictation'
    | '/settings/external-apps'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/menu-bar'
    | '/settings/open-source-licenses'
    | '/settings/permissions'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/quick-access'
    | '/settings/recording'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/updates'
    | '/settings/workspaces'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/_chat/external-apps'
    | '/_chat/inbox'
    | '/_chat/linked-work'
    | '/_chat/pull-requests'
    | '/_chat/recordings'
    | '/_chat/services'
    | '/_chat/workspaces'
    | '/projects/$projectKey'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/annotations'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/capture'
    | '/settings/capture-history'
    | '/settings/cloud-uploads'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/dictation'
    | '/settings/external-apps'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/menu-bar'
    | '/settings/open-source-licenses'
    | '/settings/permissions'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/quick-access'
    | '/settings/recording'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/settings/updates'
    | '/settings/workspaces'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  WelcomeRoute: typeof WelcomeRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/updates': {
      id: '/settings/updates'
      path: '/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof SettingsUpdatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/snap-shot': {
      id: '/settings/snap-shot'
      path: '/snap-shot'
      fullPath: '/settings/snap-shot'
      preLoaderRoute: typeof SettingsSnapShotRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/recording': {
      id: '/settings/recording'
      path: '/recording'
      fullPath: '/settings/recording'
      preLoaderRoute: typeof SettingsRecordingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quick-access': {
      id: '/settings/quick-access'
      path: '/quick-access'
      fullPath: '/settings/quick-access'
      preLoaderRoute: typeof SettingsQuickAccessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/open-source-licenses': {
      id: '/settings/open-source-licenses'
      path: '/open-source-licenses'
      fullPath: '/settings/open-source-licenses'
      preLoaderRoute: typeof SettingsOpenSourceLicensesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/menu-bar': {
      id: '/settings/menu-bar'
      path: '/menu-bar'
      fullPath: '/settings/menu-bar'
      preLoaderRoute: typeof SettingsMenuBarRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/external-apps': {
      id: '/settings/external-apps'
      path: '/external-apps'
      fullPath: '/settings/external-apps'
      preLoaderRoute: typeof SettingsExternalAppsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dictation': {
      id: '/settings/dictation'
      path: '/dictation'
      fullPath: '/settings/dictation'
      preLoaderRoute: typeof SettingsDictationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cloud-uploads': {
      id: '/settings/cloud-uploads'
      path: '/cloud-uploads'
      fullPath: '/settings/cloud-uploads'
      preLoaderRoute: typeof SettingsCloudUploadsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/capture-history': {
      id: '/settings/capture-history'
      path: '/capture-history'
      fullPath: '/settings/capture-history'
      preLoaderRoute: typeof SettingsCaptureHistoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/capture': {
      id: '/settings/capture'
      path: '/capture'
      fullPath: '/settings/capture'
      preLoaderRoute: typeof SettingsCaptureRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/annotations': {
      id: '/settings/annotations'
      path: '/annotations'
      fullPath: '/settings/annotations'
      preLoaderRoute: typeof SettingsAnnotationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/workspaces': {
      id: '/_chat/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof ChatWorkspacesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/services': {
      id: '/_chat/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ChatServicesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/recordings': {
      id: '/_chat/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof ChatRecordingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/linked-work': {
      id: '/_chat/linked-work'
      path: '/linked-work'
      fullPath: '/linked-work'
      preLoaderRoute: typeof ChatLinkedWorkRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/inbox': {
      id: '/_chat/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ChatInboxRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/external-apps': {
      id: '/_chat/external-apps'
      path: '/external-apps'
      fullPath: '/external-apps'
      preLoaderRoute: typeof ChatExternalAppsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatExternalAppsRoute: typeof ChatExternalAppsRoute
  ChatInboxRoute: typeof ChatInboxRoute
  ChatLinkedWorkRoute: typeof ChatLinkedWorkRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatRecordingsRoute: typeof ChatRecordingsRoute
  ChatServicesRoute: typeof ChatServicesRoute
  ChatWorkspacesRoute: typeof ChatWorkspacesRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatExternalAppsRoute: ChatExternalAppsRoute,
  ChatInboxRoute: ChatInboxRoute,
  ChatLinkedWorkRoute: ChatLinkedWorkRoute,
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatRecordingsRoute: ChatRecordingsRoute,
  ChatServicesRoute: ChatServicesRoute,
  ChatWorkspacesRoute: ChatWorkspacesRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAnnotationsRoute: typeof SettingsAnnotationsRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCaptureRoute: typeof SettingsCaptureRoute
  SettingsCaptureHistoryRoute: typeof SettingsCaptureHistoryRoute
  SettingsCloudUploadsRoute: typeof SettingsCloudUploadsRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsDictationRoute: typeof SettingsDictationRoute
  SettingsExternalAppsRoute: typeof SettingsExternalAppsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsMenuBarRoute: typeof SettingsMenuBarRoute
  SettingsOpenSourceLicensesRoute: typeof SettingsOpenSourceLicensesRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsQuickAccessRoute: typeof SettingsQuickAccessRoute
  SettingsRecordingRoute: typeof SettingsRecordingRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRoute
  SettingsSnapShotRoute: typeof SettingsSnapShotRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsUpdatesRoute: typeof SettingsUpdatesRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAnnotationsRoute: SettingsAnnotationsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCaptureRoute: SettingsCaptureRoute,
  SettingsCaptureHistoryRoute: SettingsCaptureHistoryRoute,
  SettingsCloudUploadsRoute: SettingsCloudUploadsRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsDictationRoute: SettingsDictationRoute,
  SettingsExternalAppsRoute: SettingsExternalAppsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsMenuBarRoute: SettingsMenuBarRoute,
  SettingsOpenSourceLicensesRoute: SettingsOpenSourceLicensesRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsQuickAccessRoute: SettingsQuickAccessRoute,
  SettingsRecordingRoute: SettingsRecordingRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRoute,
  SettingsSnapShotRoute: SettingsSnapShotRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsUpdatesRoute: SettingsUpdatesRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  WelcomeRoute: WelcomeRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
