import AppKit
import Combine
import CryptoKit
import GRDB

struct ClipboardTextRecord: Identifiable, Codable, Equatable, FetchableRecord, PersistableRecord {
  let id: UUID
  let text: String
  let contentHash: String
  var copiedAt: Date

  var preview: String {
    String(text.prefix(400)).trimmingCharacters(in: .whitespacesAndNewlines)
  }
}

/// Local, opt-in text history. Clipboard contents are never included in diagnostics.
@MainActor
final class ClipboardTextHistoryStore: ObservableObject {
  static let shared = ClipboardTextHistoryStore(
    dbPool: try? DatabaseManager.shared().dbPool,
    pasteboard: .general,
    defaults: .standard
  )

  static let maximumTextBytes = 64 * 1024
  static let maximumRecordCount = 500
  static let retentionDays = 30

  @Published private(set) var records: [ClipboardTextRecord] = []
  @Published private(set) var errorMessage: String?

  private let dbPool: DatabasePool?
  private let pasteboard: NSPasteboard
  private let defaults: UserDefaults
  private var lastChangeCount: Int
  private var wasEnabled: Bool
  private var timer: AnyCancellable?
  private var lastPrunedAt = Date.distantPast

  // No actor-bound cleanup: avoid the Swift 6.2 main-actor deinit back-deployment shim.
  nonisolated deinit {}

  init(dbPool: DatabasePool?, pasteboard: NSPasteboard, defaults: UserDefaults) {
    self.dbPool = dbPool
    self.pasteboard = pasteboard
    self.defaults = defaults
    lastChangeCount = pasteboard.changeCount
    wasEnabled = defaults.bool(forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    prune()
    refresh()
  }

  func start() {
    guard timer == nil, !DatabaseManager.isRunningUnderXCTest else { return }
    // Start with future copies; do not collect a clipboard left over from before launch.
    lastChangeCount = pasteboard.changeCount
    timer = Timer.publish(every: 0.5, tolerance: 0.1, on: .main, in: .common)
      .autoconnect()
      .sink { [weak self] _ in self?.poll() }
  }

  func stop() {
    timer?.cancel()
    timer = nil
  }

  func poll(now: Date = Date()) {
    if now.timeIntervalSince(lastPrunedAt) >= 3600 {
      prune(now: now)
      refresh()
    }

    let enabled = defaults.bool(forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    defer { wasEnabled = enabled }
    guard enabled, wasEnabled else {
      // Discard changes made while paused, including the clipboard at resume time.
      lastChangeCount = pasteboard.changeCount
      return
    }

    let changeCount = pasteboard.changeCount
    guard changeCount != lastChangeCount else { return }
    lastChangeCount = changeCount
    guard let text = Self.regularText(from: pasteboard),
      pasteboard.changeCount == changeCount else { return }
    save(text, at: now)
  }

  static func regularText(from pasteboard: NSPasteboard) -> String? {
    let types = Set((pasteboard.types ?? []).map(\.rawValue))
    // Honor clipboard-manager conventions, including legacy password-manager markers.
    let excludedTypes: Set<String> = [
      "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
      "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType",
      NSPasteboard.PasteboardType.fileURL.rawValue,
      NSPasteboard.PasteboardType.png.rawValue,
      NSPasteboard.PasteboardType.tiff.rawValue,
      "NSFilenamesPboardType",
    ]
    guard types.isDisjoint(with: excludedTypes),
      let text = pasteboard.string(forType: .string),
      !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
      text.utf8.count <= maximumTextBytes else { return nil }
    return text
  }

  private func save(_ text: String, at date: Date) {
    guard let dbPool else {
      errorMessage = "Clipboard history is unavailable. Restart Cinderdeck to try again."
      return
    }
    let hash = SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
    do {
      try dbPool.write { db in
        if var existing = try ClipboardTextRecord.filter(Column("contentHash") == hash).fetchOne(db) {
          existing.copiedAt = date
          try existing.update(db)
        } else {
          try ClipboardTextRecord(id: UUID(), text: text, contentHash: hash, copiedAt: date).insert(db)
        }
        try Self.prune(in: db, now: date)
      }
      refresh()
    } catch {
      errorMessage = "Could not save clipboard text. Restart Cinderdeck to try again."
    }
  }

  @discardableResult
  func copy(_ record: ClipboardTextRecord) -> Bool {
    pasteboard.clearContents()
    let success = pasteboard.setString(record.text, forType: .string)
    // Recopied history stays in place and does not create a duplicate on the next poll.
    lastChangeCount = pasteboard.changeCount
    if !success { errorMessage = "Could not copy this text. Please try again." }
    return success
  }

  func remove(_ id: UUID) {
    mutate { db in _ = try ClipboardTextRecord.deleteOne(db, id: id) }
  }

  func clear() {
    mutate { db in _ = try ClipboardTextRecord.deleteAll(db) }
  }

  func prune(now: Date = Date()) {
    mutate { db in try Self.prune(in: db, now: now) }
    lastPrunedAt = now
  }

  private static func prune(in db: Database, now: Date) throws {
    let cutoff = now.addingTimeInterval(-Double(retentionDays) * 86400)
    try ClipboardTextRecord.filter(Column("copiedAt") < cutoff).deleteAll(db)
    try db.execute(sql: """
      DELETE FROM clipboardTextRecord WHERE id NOT IN (
        SELECT id FROM clipboardTextRecord ORDER BY copiedAt DESC, id DESC LIMIT ?
      )
      """, arguments: [maximumRecordCount])
  }

  private func mutate(_ body: (Database) throws -> Void) {
    guard let dbPool else {
      errorMessage = "Clipboard history is unavailable. Restart Cinderdeck to try again."
      return
    }
    do {
      try dbPool.write(body)
      refresh()
    } catch {
      errorMessage = "Could not update clipboard history. Please try again."
    }
  }

  func refresh() {
    guard let dbPool else { return }
    do {
      records = try dbPool.read { db in
        try ClipboardTextRecord.order(Column("copiedAt").desc, Column("id").desc).fetchAll(db)
      }
      errorMessage = nil
    } catch {
      errorMessage = "Could not load clipboard history. Restart Cinderdeck to try again."
    }
  }
}
