import * as Schema from "effect/Schema";

// Named keys plus US-layout characters, so Excel shortcuts (F2, F4, F9, Cmd-Shift-L,
// Ctrl-Shift-arrows) are expressible. Text entry uses "type", not key-by-key input.
export const DEBUG_KEYS = [
  "Enter",
  "Tab",
  "Escape",
  "Backspace",
  "Delete",
  "Space",
  "ArrowLeft",
  "ArrowRight",
  "ArrowDown",
  "ArrowUp",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "-",
  "=",
  "[",
  "]",
  "\\",
  ";",
  "'",
  ",",
  ".",
  "/",
  "`",
] as const;
export type DebugKey = (typeof DEBUG_KEYS)[number];

const normalized = Schema.Number.check(Schema.isBetween({ minimum: 0, maximum: 1 }));
// Native window input shared by debug commands and benchmark steps. Coordinates are
// normalized to the selected window.
export const NativeInputFields = {
  x: Schema.optionalKey(normalized),
  y: Schema.optionalKey(normalized),
  button: Schema.optionalKey(Schema.Literals(["left", "right"])),
  clickCount: Schema.optionalKey(Schema.Literals([1, 2])),
  // Drag destination, normalized like x/y.
  toX: Schema.optionalKey(normalized),
  toY: Schema.optionalKey(normalized),
  // Element reference from the most recent accessibility snapshot of this window.
  ref: Schema.optionalKey(Schema.String.check(Schema.isPattern(/^e\d{1,4}$/))),
  text: Schema.optionalKey(Schema.String.check(Schema.isMaxLength(4000))),
  key: Schema.optionalKey(Schema.Literals(DEBUG_KEYS)),
  modifiers: Schema.optionalKey(
    Schema.Array(Schema.Literals(["meta", "alt", "shift", "control"])).check(Schema.isMaxLength(4)),
  ),
  deltaX: Schema.optionalKey(Schema.Int.check(Schema.isBetween({ minimum: -1200, maximum: 1200 }))),
  deltaY: Schema.optionalKey(Schema.Int.check(Schema.isBetween({ minimum: -1200, maximum: 1200 }))),
};
export const NormalizedRegion = Schema.Struct({
  x: normalized,
  y: normalized,
  width: normalized,
  height: normalized,
});
export type NormalizedRegion = typeof NormalizedRegion.Type;
