import AppKit
import XCTest
@testable import Snapzy

@MainActor
final class ClipboardTextHistoryStoreTests: XCTestCase {
  private var directory: URL!
  private var defaults: UserDefaults!
  private var suite: String!
  private var pasteboard: NSPasteboard!
  private var database: DatabaseManager!
  private var store: ClipboardTextHistoryStore!

  override func setUpWithError() throws {
    suite = "SnapzyTests.ClipboardTextHistory.\(UUID().uuidString)"
    defaults = UserDefaults(suiteName: suite)
    defaults.set(true, forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    pasteboard = NSPasteboard.withUniqueName()
    directory = FileManager.default.temporaryDirectory.appendingPathComponent(suite)
    database = try DatabaseManager.openDatabase(at: directory.appendingPathComponent("history.db"))
    store = ClipboardTextHistoryStore(dbPool: database.dbPool, pasteboard: pasteboard, defaults: defaults)
  }

  override func tearDownWithError() throws {
    store.stop()
    store = nil
    database = nil
    pasteboard.releaseGlobally()
    defaults.removePersistentDomain(forName: suite)
    try FileManager.default.removeItem(at: directory)
  }

  func testNewCopyPreservesMultilineUnicodeAndWhitespaceAcrossRelaunch() throws {
    let text = "  First line\n\tSecond line — café 🐟\n"
    write(text)
    store.poll()
    XCTAssertEqual(store.records.map(\.text), [text])

    let reopened = try DatabaseManager.openDatabase(at: directory.appendingPathComponent("history.db"))
    let restored = ClipboardTextHistoryStore(dbPool: reopened.dbPool, pasteboard: pasteboard, defaults: defaults)
    XCTAssertEqual(restored.records.map(\.text), [text])
    XCTAssertNil(restored.errorMessage)
  }

  func testExistingClipboardAtStartupIsNotCollected() {
    write("Copied before launch")
    store = ClipboardTextHistoryStore(dbPool: database.dbPool, pasteboard: pasteboard, defaults: defaults)
    store.poll()
    XCTAssertTrue(store.records.isEmpty)
  }

  func testDuplicateMovesToTopWithoutDuplicatingAndOwnCopyDoesNotReorder() throws {
    let now = Date()
    write("First")
    store.poll(now: now)
    let firstID = try XCTUnwrap(store.records.first?.id)
    write("Second")
    store.poll(now: now.addingTimeInterval(1))
    write("First")
    store.poll(now: now.addingTimeInterval(2))
    XCTAssertEqual(store.records.map(\.text), ["First", "Second"])
    XCTAssertEqual(store.records.first?.id, firstID)

    let before = store.records
    XCTAssertTrue(store.copy(try XCTUnwrap(store.records.last)))
    store.poll(now: now.addingTimeInterval(3))
    XCTAssertEqual(pasteboard.string(forType: .string), "Second")
    XCTAssertEqual(store.records, before)
  }

  func testPauseAndResumeSkipCopiesWhilePaused() {
    defaults.set(false, forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    write("Paused")
    store.poll()
    defaults.set(true, forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    store.poll()
    XCTAssertTrue(store.records.isEmpty)
    write("Resumed")
    store.poll()
    XCTAssertEqual(store.records.map(\.text), ["Resumed"])
  }

  func testMonitoringIsOptIn() {
    defaults.removeObject(forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    write("Not opted in")
    store.poll()
    XCTAssertTrue(store.records.isEmpty)
  }

  func testSensitiveTransientAndMediaRepresentationsAreNeverSaved() {
    let excluded = [
      "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
      "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
      NSPasteboard.PasteboardType.fileURL.rawValue,
      NSPasteboard.PasteboardType.png.rawValue,
      NSPasteboard.PasteboardType.tiff.rawValue,
    ]
    for type in excluded {
      write("Must not be stored")
      pasteboard.setData(Data(), forType: NSPasteboard.PasteboardType(type))
      store.poll()
      XCTAssertTrue(store.records.isEmpty, type)
    }
  }

  func testEmptyOversizedAndImageOnlyCopiesAreSkipped() {
    for text in ["", " \n\t ", String(repeating: "é", count: ClipboardTextHistoryStore.maximumTextBytes)] {
      write(text)
      store.poll()
    }
    pasteboard.clearContents()
    pasteboard.setData(Data([0, 1, 2]), forType: .png)
    store.poll()
    XCTAssertTrue(store.records.isEmpty)
  }

  func testRichTextAndURLsWithPlainTextRepresentationAreSaved() {
    write("https://example.com/a?q=clipboard")
    pasteboard.setString("https://example.com/a?q=clipboard", forType: .URL)
    store.poll()
    XCTAssertEqual(store.records.first?.text, "https://example.com/a?q=clipboard")
    write("Formatted text")
    pasteboard.setString("<b>Formatted text</b>", forType: .html)
    store.poll()
    XCTAssertEqual(store.records.count, 2)
  }

  func testDeleteAndClearLeaveCurrentClipboardUntouched() throws {
    write("First")
    store.poll()
    write("Second")
    store.poll()
    store.remove(try XCTUnwrap(store.records.first?.id))
    XCTAssertEqual(store.records.count, 1)
    store.clear()
    XCTAssertTrue(store.records.isEmpty)
    XCTAssertEqual(pasteboard.string(forType: .string), "Second")
    store.poll()
    XCTAssertTrue(store.records.isEmpty)
  }

  func testRetentionExpiresOldTextAndBoundsRecordCount() {
    let now = Date()
    write("Old")
    store.poll(now: now.addingTimeInterval(-31 * 86400))
    for index in 0...ClipboardTextHistoryStore.maximumRecordCount {
      write("Entry \(index)")
      store.poll(now: now.addingTimeInterval(Double(index)))
    }
    XCTAssertEqual(store.records.count, ClipboardTextHistoryStore.maximumRecordCount)
    XCTAssertFalse(store.records.contains { $0.text == "Old" || $0.text == "Entry 0" })
    store.prune(now: now.addingTimeInterval(32 * 86400))
    XCTAssertTrue(store.records.isEmpty)
  }

  func testUnavailableDatabaseShowsErrorWithoutChangingClipboard() {
    let unavailable = ClipboardTextHistoryStore(dbPool: nil, pasteboard: pasteboard, defaults: defaults)
    write("Still available to paste")
    unavailable.poll()
    XCTAssertNotNil(unavailable.errorMessage)
    XCTAssertEqual(pasteboard.string(forType: .string), "Still available to paste")
  }

  func testClipboardOptInCanBeImportedFromConfiguration() {
    defaults.set(false, forKey: PreferencesKeys.clipboardTextHistoryEnabled)
    let result = SnapzyConfigurationImporter.importTOML("""
      schema_version = 1
      [history]
      clipboard_text_enabled = true
      """, defaults: defaults)
    XCTAssertFalse(result.hasErrors)
    XCTAssertTrue(defaults.bool(forKey: PreferencesKeys.clipboardTextHistoryEnabled))
  }

  private func write(_ text: String) {
    pasteboard.clearContents()
    XCTAssertTrue(pasteboard.setString(text, forType: .string))
  }
}
